### PR TITLE
Hotfix/forecast issue 13

### PR DESCRIPTION
**Pull request by cdilga**
# Description of change
Fixes the production bug in #13 with a Http 422.
Also allows full table refreshes to function correctly by adding the `active_version` messages in the Singer.io spec

# Manual QA steps
 - Run install in venv
 - Tested in a local and Amazon ECS environment with a CSV and Snowflake target. 
 - Verified that data matched source
 
# Risks
 - Ingestion is now significantly slower due to pagination. Speed could be improved by ignoring the pagination for endpoints other than `/assignments`. Due to the risk of further changes, the default behavior is to paginate all endpoints with 180 day increments. 
 - API changes again, causing further failures in production
 
# Rollback steps
 - revert this branch

### CODE REVIEW

**Review by asaf-erlich — APPROVED** [review]
Discussed with team, the tap is not working right now and the community is all agreeing this fix will improve things greatly. Working on getting this merged as quick as possible.

**Comment by asaf-erlich** [comment]
The tap should be released inside stitch with this fix. Please let us know if the issue is resolved. I hope it is.

**Comment by danwebb4** [comment]
> The tap should be released inside stitch with this fix. Please let us know if the issue is resolved. I hope it is.

It looks like the 422 error is resolved, but I am now seeing the error:

'dict' object has no attribute 'replication_keys'

The integration is still not functioning.

**Comment by asaf-erlich** [comment]
Hello @danwebb4 ,

This looks like another bug somewhere in the tap code. Do you have the full error logs including the stack trace that you can include somewhere? If possible can you create a new github issue for it?

Thank you,
-Asaf

**Comment by danwebb4** [comment]
Thanks Asaf, I have created a new issue and attached the full error logs at #20. Please let me know if there is anything else I can do to help troubleshoot.

**Pull request merged**
